version: "3.4"
services:

  central-db:
    container_name: central-db
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=central-db
      - PGDATA=/var/lib/postgresql/data/pgdata/central-db

        #  bivbonus-app:
        #    container_name: bivbonus-app
        #    build: ..
        #    ports:
        #      - "8080:8080"
        #    depends_on:
      #      - "central-db"
      #    links:
      #      - "central-db:central-db"
